title: AAPL
name: AAPL
email: aaplab1@email.arizona.edu
twitter: jvcasill
pygments: true
timezone: TIMEZONE

# Dependencies
markdown: redcarpet

# Permalinks
permalink: pretty

# Setup
tagline: 'Arizona Applied Phonetics Lab'
description: 'Website of the Arizona Applied Phonetics laboratory at the University of Arizona.'
url: http://aaplab1.github.io

author:
  name: 'Joseph V. Casillas'
  url: https://twitter.com/jvcasill

paginate:         5

# Custom vars
version: 1.0.1

github:	aaplab1
  repo: https://github.com/aaplab1