---
framework: lanyon
onefile: False
mode: selfcontained
---

<section id="introduction">
<h2 class="header-divider">Arizona Applied Phonetics Lab</h2>
 
The Arizona Applied Phonetics Laboratory consists of an active team of linguists interested in various issues pertaining to applied phonetic and psycholinguistic science. The team works together and strives to support its members so that they can all perform to the best of their abilities. Research is being carried out on topics such as: 
  
- Speech reduction (spontaneous speech production, perception and lexical processing) by speakers of English, Spanish, Japanese and Dutch
- Perception and production of Spanish and English consonants by early and late bilingual Spanish-English speakers
- Perception and production of various sounds in a Catalan-Spanish societal contact situation
- Variation and change in the intonational system of bilingual Catalan-Spanish speakers
- Processing of a Catalan-specific palatal consonant contrast by Spanish-Catalan bilinguals in the context of a merger in progress
- Processing of English-specific vowel contrasts by Spanish-English bilinguals
- Production and perception of vowel sequences at word-boundaries in Spanish
- Acquisition of the English intonational system by Mandarin learners of English

The lab works closely with other Arizona labs, most prominently the Douglass Phonetics Laboratory of the Department of Linguistics, and maintains a productive relationship with the Illinois Phonetics and Phonology Laboratory and researchers at other institutions.

</section>



<style>
  .lead {
    margin-bottom: 20px;
    font-size: 1.1rem;
    font-weight: 200;
    line-height: 1.4;
    text-align: justify;
  }
</style>
