title: AAPL
tagline: ""
theme: "01"
reverse: False
description: >

url: "http://aaplab1.github.io"
author:
  name: "AAPL"
  github: "aaplab1"
  twitter: ""


sidebar:
  - {item: Members, href: '/members', icon: 'cogs'}
  - {item: Research, href: '/research', icon: 'pencil-square'}
  - {item: Equipment, href: '/equipment', icon: 'archive'}
  - {item: Resources, href: '/resources', icon: 'code'}




